#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx --no-install commitlint --edit $1

# <type>[<scope>]:<subject>
# //need placeholder a newline if adding body part
# [<body>]

# Type 字段包含:

# build: 主要目的是修改项目构建系统(例如glup，webpack，rollup的配置等)的提交
# ci:主要目的是修改项目继续完成集成流程(例如Travis，Jenkins，GitLab CI,Circle)的提交
# doc：对应的文档更新
# feat：项目中的新增功能(feature)
# fix： bug修复
# pref：性能优化
# refactor：重构代码(既没有新功能，也没有修复bug)
# style：不影响程序逻辑的代码修改(更加规范，加入空白符，补全分号)
# test：新增测试用例或是更新现有测试
# revert：回滚某个更早之前的提交
# chore： 不属于以上类型的其他类型

# scope用于说明 commit 影响的范围，比如数据层、控制层、视图层等等。

# subject是 commit 目的的简短描述，不超过50个字符

# Body 部分是对本次 commit 的详细描述，可以分成多行

# Footer用来关闭 Issue或以BREAKING CHANGE开头，后面是对变动的描述、以及变动理由和迁移方法